[package]
name = "shapeshift"
version = "0.1.0"
authors = ["Logan Saether <Lsaether@protonmail.com>"]
description = "A library wrapper around the Shapeshift API written in Rust."

[dependencies]
clap = "2.31.2"
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term = "0.4.6"
